steps:
  - name: 'gcr.io/cloud-builders/go'
    id: Executando testes
    args:
      - 'test'
      - 'sum'
    env: ['GOPATH=.']

  - name: 'gcr.io/cloud-builders/go'
    id: Executando go build
    args:
      - 'build'
      - '-o'
      - 'sum'
      - '.'
    env: ['GOPATH=.']

  - name: 'gcr.io/cloud-builders/docker'
    id: Executando docker build
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/go-challenge:latest'
      - '.'

images:
  - 'gcr.io/$PROJECT_ID/go-challenge:latest'